services:
  car:
    build:
      context: .
      dockerfile: Dockerfile.jazzy
    image: pros_car:jazzy
    env_file:
      - .env
    environment:
      ROS_DISTRO: jazzy
    volumes:
      - ./src:/workspaces/src:ro
      - ./car_control_for_docker_compose.sh:/workspaces/car_control_for_docker_compose.sh:ro
    networks:
      - my_bridge_network
    ports:
      - "9090:9090"
    command: ./car_control_for_docker_compose.sh

networks:
  my_bridge_network:
    driver: bridge
