services:
  car:
    image: ghcr.io/screamlab/pros_car_docker_image:latest
    env_file:
      - .env
    volumes:
      - ./src:/workspaces/src
      - ./launch:/workspaces/launch
      - ./task_bringup.sh:/workspaces/task_bringup.sh
    networks:
      - my_bridge_network
    command: ./task_bringup.sh

networks:
  my_bridge_network:
    external: true
    name: compose_my_bridge_network
