services:
  ros_topic_bridge:
    image: ${PROS_DRIVER_IMAGE:-ghcr.io/screamlab/pros_jetson_driver_image:0.1.1}
    env_file:
      - .env
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: "python3 /workspace/demo/ros_topic_bridge.py /workspace/demo/bridge_config.yaml"
    restart: unless-stopped

networks:
  my_bridge_network:
    name: compose_my_bridge_network
    external: true
