services:
  localization:
    image: ${PROS_DRIVER_IMAGE:-ghcr.io/screamlab/pros_jetson_driver_image:0.1.0}
    env_file:
      - .env
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: "ros2 launch /workspace/demo/localization.xml"

  rosbridge:
    image: ${PROS_BASE_IMAGE:-ghcr.io/screamlab/pros_base_image:0.0.2}
    env_file:
      - .env
    networks:
      - my_bridge_network
    ports:
      - 9090:9090
    command: " ros2 launch rosbridge_server rosbridge_websocket_launch.xml"

# This reuses the shared PROS bridge network.
# Create it with: docker network create --driver bridge compose_my_bridge_network
# You can see the network by docker network ls
networks:
  my_bridge_network:
    name: compose_my_bridge_network
    external: true
