services:
  rosbridge:
    image: ${PROS_BASE_IMAGE:-ghcr.io/screamlab/pros_base_image:0.0.2}
    env_file:
      - .env
    networks:
      - my_bridge_network
    ports:
      - 9090:9090
    command: "ros2 launch rosbridge_server rosbridge_websocket_launch.xml"
  foxglove_bridge:
    image: ${FOXGLOVE_BRIDGE_IMAGE:-us-central1-docker.pkg.dev/foxglove-images/images/foxglove_bridge:ros-humble-v3.2.6}
    env_file:
      - .env
    networks:
      - my_bridge_network
    ports:
      - 8765:8765

# This reuses the shared PROS bridge network.
# Create it with: docker network create --driver bridge compose_my_bridge_network
# You can see the network by docker network ls
networks:
  my_bridge_network:
    name: compose_my_bridge_network
    external: true
