services:
  map:
    image: ${PROS_DRIVER_IMAGE:-ghcr.io/screamlab/pros_jetson_driver_image:0.1.0}
    env_file:
      - .env
    volumes:
      - ./demo/map/map01:/map
    networks:
      - my_bridge_network
    command: "ros2 run nav2_map_server map_saver_cli -f /map/map01"

# This reuses the shared PROS bridge network.
# Create it with: docker network create --driver bridge compose_my_bridge_network
# You can see the network by docker network ls
networks:
  my_bridge_network:
    name: compose_my_bridge_network
    external: true
